apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-proj-deployment
  labels:
    app: python-proj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-proj
  template:
    metadata:
      labels:
        app: python-proj
    spec:
      containers:
      - name: python-proj
        image: brightlee14/python-proj:latest
        ports:
        - containerPort: 5000
